export type PuzzleGoal = 'win' | 'draw'

export type Puzzle = {
  id: string
  title: string
  category: string
  /** 书中局号，便于对照纸书 */
  bookNo?: string
  difficulty: 1 | 2 | 3 | 4 | 5
  fen: string
  winSide: 'red' | 'black'
  goal: PuzzleGoal
  tip?: string
}

/**
 * 目录结构对照陈松顺《中国象棋实用残局增订本》
 * 局面为按公开残局结论自拟的教学局面，非书中原图扫描。
 */
export const CATEGORIES = [
  '原本·马类',
  '原本·炮类',
  '原本·兵类',
  '原本·车类',
  '增订·马类',
  '增订·双马双炮',
  '增订·兵类',
  '增订·车类',
  '增订·基本杀法',
  '增订·棋谚图解',
  '增订·实战选评',
] as const

export const PUZZLES: Puzzle[] = [
  // ========== 原本·马类（24） ==========
  {
    id: 'o-m-01',
    bookNo: '一',
    title: '马取单士',
    category: '原本·马类',
    difficulty: 2,
    fen: '4k4/4a4/9/9/9/9/9/4N4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '禁将、逼士，马挂角/卧槽收官。',
  },
  {
    id: 'o-m-02',
    bookNo: '二',
    title: '马巧胜双士',
    category: '原本·马类',
    difficulty: 3,
    fen: '3aka3/9/9/9/9/9/4N4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双士粘性大，需等着与马步节奏，逼士离位。',
  },
  {
    id: 'o-m-03',
    bookNo: '三',
    title: '马胜单象（将象归边负）',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/2b6/9/9/9/4N4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '将象同侧归边时可胜；控象眼、赶象出宫。',
  },
  {
    id: 'o-m-04',
    bookNo: '四',
    title: '马不胜单象（左将右象和）',
    category: '原本·马类',
    difficulty: 3,
    fen: '2k6/9/6b2/9/9/9/4N4/9/9/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '正和形：将象分居两侧。红执马体验为何难胜；可换执黑练守。',
  },
  {
    id: 'o-m-05',
    bookNo: '五',
    title: '马取单卒（例一）',
    category: '原本·马类',
    difficulty: 2,
    fen: '4k4/9/9/4p4/9/9/4N4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '先禁卒升变路线，再运马捉卒或逼将。',
  },
  {
    id: 'o-m-06',
    bookNo: '六',
    title: '马取单卒（例二）',
    category: '原本·马类',
    difficulty: 2,
    fen: '3k5/9/9/9/4p4/9/3N5/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '卒在肋道时注意堵截，防止卒过河换势。',
  },
  {
    id: 'o-m-07',
    bookNo: '七',
    title: '马和炮双士',
    category: '原本·马类',
    difficulty: 3,
    fen: '3aka3/9/9/9/9/9/4N4/4c4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马对炮双士多为正和；体验炮士联防。',
  },
  {
    id: 'o-m-08',
    bookNo: '八',
    title: '马巧和炮卒双士',
    category: '原本·马类',
    difficulty: 4,
    fen: '3aka3/9/9/4p4/9/9/4N4/4c4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '多卒时仍有巧和可能，重在兑子与占位。',
  },
  {
    id: 'o-m-09',
    bookNo: '九',
    title: '马当仕和车',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/4N4/9/9/9/4r4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马占仕位顶车，经典守和思路。',
  },
  {
    id: 'o-m-10',
    bookNo: '十',
    title: '马当相和车',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/4N4/9/9/4r4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马占相位支应，防车切入。',
  },
  {
    id: 'o-m-11',
    bookNo: '十一',
    title: '马双相和车（高相可和）',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/2B2B3/4N4/9/4r4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '高相连环可和单车。',
  },
  {
    id: 'o-m-12',
    bookNo: '十二',
    title: '马双象不和车（低象不和）',
    category: '原本·马类',
    difficulty: 3,
    // 执车方（红）破低象马
    fen: '4k4/9/4n4/2b2b3/9/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对方低象时，单车可破马双象。',
  },
  {
    id: 'o-m-13',
    bookNo: '十三',
    title: '马兵相巧和车',
    category: '原本·马类',
    difficulty: 4,
    fen: '4k4/9/2B6/4N4/4P4/4r4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马兵相联防顶车，注意兵勿乱进。',
  },
  {
    id: 'o-m-14',
    bookNo: '十四',
    title: '马低卒不胜双仕兵',
    category: '原本·马类',
    difficulty: 3,
    fen: '3a1a3/4k4/9/4p4/9/4n4/4P4/4A4/4A4/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '红有双仕兵守马低卒，多为不胜/和形。',
  },
  {
    id: 'o-m-15',
    bookNo: '十五',
    title: '马兵巧胜士象全',
    category: '原本·马类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/9/4P4/4N4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '高难度巧胜：运马赶象、借兵破士。',
  },
  {
    id: 'o-m-16',
    bookNo: '十六',
    title: '马卒不胜仕相全（正和局）',
    category: '原本·马类',
    difficulty: 3,
    fen: '3aKa3/9/2B2B3/9/4p4/4n4/9/9/9/4k4 b',
    winSide: 'black',
    goal: 'draw',
    tip: '执黑马卒攻红仕相全：体会正和。',
  },
  {
    id: 'o-m-17',
    bookNo: '十七',
    title: '马低卒不胜单缺仕',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/4a4/2b2b3/9/4p4/4n4/9/4A4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '红守单缺仕，马低卒难胜。',
  },
  {
    id: 'o-m-18',
    bookNo: '十八',
    title: '马低卒不胜单缺相',
    category: '原本·马类',
    difficulty: 3,
    fen: '3aka3/9/2b6/9/4p4/4n4/9/2B6/4A4/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单缺相防守马低卒，注意象位。',
  },
  {
    id: 'o-m-19',
    bookNo: '十九',
    title: '马高兵必胜单缺象',
    category: '原本·马类',
    difficulty: 4,
    fen: '3aka3/9/2b6/9/4P4/4N4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '高兵到位则必胜单缺象，先定中再破士。',
  },
  {
    id: 'o-m-20',
    bookNo: '二十',
    title: '马兵胜炮象',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/2b6/9/4P4/4N4/9/4c4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马兵配合捉炮或逼象，形成杀势。',
  },
  {
    id: 'o-m-21',
    bookNo: '二十一',
    title: '马低卒不胜单炮',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/9/9/4p4/4n4/9/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单炮可顶马低卒，红方体会守和。',
  },
  {
    id: 'o-m-22',
    bookNo: '二十二',
    title: '马高兵单相巧胜马士',
    category: '原本·马类',
    difficulty: 4,
    fen: '3ak4/9/4n4/9/4P4/4N4/2B6/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '有相助攻，借高兵兑子入局。',
  },
  {
    id: 'o-m-23',
    bookNo: '二十三',
    title: '马高兵必胜炮士',
    category: '原本·马类',
    difficulty: 3,
    fen: '3ak4/9/9/9/4P4/4N4/9/4c4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '高兵禁炮，马士配合得子或杀。',
  },
  {
    id: 'o-m-24',
    bookNo: '二十四',
    title: '马兵（未过河）胜双象',
    category: '原本·马类',
    difficulty: 4,
    fen: '4k4/9/2b2b3/9/9/4P4/4N4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '兵未过河仍可胜双象，关键在控象与推进时机。',
  },

  // ========== 原本·炮类（16） ==========
  {
    id: 'o-c-25',
    bookNo: '二十五',
    title: '炮仕胜双士',
    category: '原本·炮类',
    difficulty: 2,
    fen: '3aka3/9/9/9/9/9/9/4C4/4A4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '有仕作炮架，破双士。',
  },
  {
    id: 'o-c-26',
    bookNo: '二十六',
    title: '炮士象全不胜单仕相',
    category: '原本·炮类',
    difficulty: 3,
    fen: '3aKa3/4A4/2B6/9/9/9/2b2b3/4c4/4a4/3k5 b',
    winSide: 'black',
    goal: 'draw',
    tip: '执黑炮士象全攻红单仕相：体会不胜。',
  },
  {
    id: 'o-c-27',
    bookNo: '二十七',
    title: '炮双仕和车',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/9/9/9/4r4/9/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '炮双仕顶车正和。',
  },
  {
    id: 'o-c-28',
    bookNo: '二十八',
    title: '炮双相和车（低相可和）',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/9/9/9/4r4/2B2B3/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '低相形可和单车。',
  },
  {
    id: 'o-c-29',
    bookNo: '二十九',
    title: '炮双象不和车（高象不和）',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/2b2b3/4c4/9/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '执车破高象炮双象。',
  },
  {
    id: 'o-c-30',
    bookNo: '三十',
    title: '炮双仕必和三高卒',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/9/2p1p1p2/9/9/9/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '炮双仕守三高卒。',
  },
  {
    id: 'o-c-31',
    bookNo: '三十一',
    title: '炮仕相全和车卒',
    category: '原本·炮类',
    difficulty: 4,
    fen: '4k4/9/2B6/4p4/9/4r4/9/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '全士相炮守车卒。',
  },
  {
    id: 'o-c-32',
    bookNo: '三十二',
    title: '炮巧和炮卒士',
    category: '原本·炮类',
    difficulty: 4,
    fen: '3ak4/9/9/4p4/9/9/9/4C4/4c4/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单炮巧和炮卒士。',
  },
  {
    id: 'o-c-33',
    bookNo: '三十三',
    title: '炮低兵禁单象（将上顶不和）',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/2b6/9/9/4P4/9/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '低兵禁象，逼将上顶可胜。',
  },
  {
    id: 'o-c-34',
    bookNo: '三十四',
    title: '炮低卒象不胜单相（巧和）',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/2b6/9/4p4/4c4/2B6/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单相巧和炮低卒象。',
  },
  {
    id: 'o-c-35',
    bookNo: '三十五',
    title: '炮高兵必胜单象',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/2b6/9/4P4/9/9/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '高兵作架或逼宫，必胜单象。',
  },
  {
    id: 'o-c-36',
    bookNo: '三十六',
    title: '炮底兵仕相必胜单士象',
    category: '原本·炮类',
    difficulty: 4,
    fen: '3ak4/9/2b6/9/9/9/4P4/4C4/4A4/3KB4 w',
    winSide: 'red',
    goal: 'win',
    tip: '底兵配合仕相炮，破单士象。',
  },
  {
    id: 'o-c-37',
    bookNo: '三十七',
    title: '炮底兵仕对单士象的胜和规律',
    category: '原本·炮类',
    difficulty: 4,
    fen: '3ak4/9/2b6/9/9/9/4P4/4C4/4A4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书中规律：仕位相、将位决定胜和。',
  },
  {
    id: 'o-c-38',
    bookNo: '三十八',
    title: '炮双过河兵可和车',
    category: '原本·炮类',
    difficulty: 4,
    fen: '4k4/9/9/2P2P3/9/4r4/9/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '双过河兵+炮顶车。',
  },
  {
    id: 'o-c-39',
    bookNo: '三十九',
    title: '炮兵仕相全胜士象全（沉炮法）',
    category: '原本·炮类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/9/4P4/9/2B6/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'win',
    tip: '例一：沉底炮法破士象全。',
  },
  {
    id: 'o-c-40',
    bookNo: '四十',
    title: '炮兵仕相全胜士象全（破羊角士）',
    category: '原本·炮类',
    difficulty: 5,
    fen: '4ka3/3a5/2b2b3/9/4P4/9/2B6/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'win',
    tip: '例二：针对羊角士的破法。',
  },

  // ========== 原本·兵类（11） ==========
  {
    id: 'o-p-41',
    bookNo: '四十一',
    title: '一兵单相巧胜单士',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3ak4/9/9/9/4P4/9/2B6/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '兵相配合巧胜单士。',
  },
  {
    id: 'o-p-42',
    bookNo: '四十二',
    title: '单兵和炮士象',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3ak4/9/2b6/9/4P4/9/9/4c4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单兵难破炮士象，多为和。',
  },
  {
    id: 'o-p-43',
    bookNo: '四十三',
    title: '兵仕巧和双卒双士',
    category: '原本·兵类',
    difficulty: 4,
    fen: '3aka3/9/9/2p2p3/9/9/4P4/4A4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '兵仕巧守双卒双士。',
  },
  {
    id: 'o-p-44',
    bookNo: '四十四',
    title: '双兵巧胜单缺象',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3aka3/9/2b6/9/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双兵联手破单缺象。',
  },
  {
    id: 'o-p-45',
    bookNo: '四十五',
    title: '双兵巧胜单缺士',
    category: '原本·兵类',
    difficulty: 3,
    fen: '4ka3/9/2b2b3/9/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双兵破单缺士。',
  },
  {
    id: 'o-p-46',
    bookNo: '四十六',
    title: '双兵巧胜士象全',
    category: '原本·兵类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/9/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双兵巧胜士象全，重在联兵与塞象眼。',
  },
  {
    id: 'o-p-47',
    bookNo: '四十七',
    title: '双兵不胜单士象',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3ak4/9/2b6/9/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单士象可顶双兵。',
  },
  {
    id: 'o-p-48',
    bookNo: '四十八',
    title: '双兵对单卒象',
    category: '原本·兵类',
    difficulty: 3,
    fen: '4k4/9/2b6/4p4/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书中胜和分支练习。',
  },
  {
    id: 'o-p-49',
    bookNo: '四十九',
    title: '双兵对单卒士',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3ak4/9/9/4p4/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双兵对卒士，注意兑兵时机。',
  },
  {
    id: 'o-p-50',
    bookNo: '五十',
    title: '三兵胜士象全（例一）',
    category: '原本·兵类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/9/2P1P1P2/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '三兵例胜士象全。',
  },
  {
    id: 'o-p-51',
    bookNo: '五十一',
    title: '三兵胜士象全（例二）',
    category: '原本·兵类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/2P6/4P4/6P2/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '三兵另一典型阵形。',
  },

  // ========== 原本·车类（19） ==========
  {
    id: 'o-r-52',
    bookNo: '五十二',
    title: '车不胜仕相全（正和局）',
    category: '原本·车类',
    difficulty: 2,
    fen: '3aKa3/9/2B2B3/9/9/9/9/4r4/9/3k5 b',
    winSide: 'black',
    goal: 'draw',
    tip: '执黑单车攻仕相全：正和，体验守方联防。',
  },
  {
    id: 'o-r-53',
    bookNo: '五十三',
    title: '车巧胜士象全（例一）',
    category: '原本·车类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/9/9/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '单车巧胜士象全，需精确控肋。',
  },
  {
    id: 'o-r-54',
    bookNo: '五十四',
    title: '车巧胜士象全（例二）',
    category: '原本·车类',
    difficulty: 4,
    fen: '4ka3/4a4/2b2b3/9/9/9/9/9/4R4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '另一典型入局次序。',
  },
  {
    id: 'o-r-55',
    bookNo: '五十五',
    title: '车必胜马双士（例一）',
    category: '原本·车类',
    difficulty: 3,
    fen: '3aka3/9/4n4/9/9/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车必胜马双士。',
  },
  {
    id: 'o-r-56',
    bookNo: '五十六',
    title: '车必胜马双士（例二）',
    category: '原本·车类',
    difficulty: 3,
    fen: '3aka3/9/9/4n4/9/9/9/9/4R4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马位不同时的必胜法。',
  },
  {
    id: 'o-r-57',
    bookNo: '五十七',
    title: '车炮胜单车（车正则胜）',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/9/9/9/4r4/9/4C4/4R4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车占中肋则车炮必胜单车。',
  },
  {
    id: 'o-r-58',
    bookNo: '五十八',
    title: '车炮胜单车（迫车离中胜）',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/9/9/9/9/4r4/4C4/4R4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '先迫对方车离中，再入局。',
  },
  {
    id: 'o-r-59',
    bookNo: '五十九',
    title: '车底兵胜单车（车正则胜）',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/9/9/9/4r4/4P4/9/4R4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '底兵+中车胜单车。',
  },
  {
    id: 'o-r-60',
    bookNo: '六十',
    title: '车低兵仕胜车士（士遮头不和）',
    category: '原本·车类',
    difficulty: 4,
    fen: '3ak4/9/9/9/9/4r4/4P4/4R4/4A4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '破单车保士：士遮头则不和。',
  },
  {
    id: 'o-r-61',
    bookNo: '六十一',
    title: '车仕和车低卒（单车保剑）',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/9/9/4p4/4r4/9/4R4/4A4/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '又名「单车保剑」：车仕守车低卒。',
  },
  {
    id: 'o-r-62',
    bookNo: '六十二',
    title: '车仕相全和车双卒',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/2B6/2p2p3/9/4r4/9/4R4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '全士相车守车双卒。',
  },
  {
    id: 'o-r-63',
    bookNo: '六十三',
    title: '车双兵巧胜车士象全',
    category: '原本·车类',
    difficulty: 5,
    fen: '3aka3/9/2b2b3/9/3P1P3/4r4/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车双兵对车士象全，高难度巧胜。',
  },
  {
    id: 'o-r-64',
    bookNo: '六十四',
    title: '车相和车卒（相在卒一边和）',
    category: '原本·车类',
    difficulty: 3,
    fen: '4k4/9/2B6/4p4/9/4r4/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '相与卒同侧可和。',
  },
  {
    id: 'o-r-65',
    bookNo: '六十五',
    title: '车兵胜车象（象不在兵一边不和）',
    category: '原本·车类',
    difficulty: 3,
    fen: '4k4/9/6b2/9/4P4/4r4/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '象不在兵一侧时可胜。',
  },
  {
    id: 'o-r-66',
    bookNo: '六十六',
    title: '车兵有仕相必胜车双象',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/2b2b3/9/4P4/4r4/2B6/4R4/4A4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '有仕相则车兵必胜车双象。',
  },
  {
    id: 'o-r-67',
    bookNo: '六十七',
    title: '车高兵必胜双卒士象全',
    category: '原本·车类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/2p2p3/4P4/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车高兵破双卒士象全。',
  },
  {
    id: 'o-r-68',
    bookNo: '六十八',
    title: '车炮双仕必和双车',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/9/9/9/3r1r3/9/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '车炮双仕守双车。',
  },
  {
    id: 'o-r-69',
    bookNo: '六十九',
    title: '双车双相巧胜车炮双士',
    category: '原本·车类',
    difficulty: 5,
    fen: '3aka3/9/9/9/9/4r4/2B2B3/4c4/3R1R3/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双车双相攻车炮双士。',
  },
  {
    id: 'o-r-70',
    bookNo: '七十',
    title: '车炮仕相全巧胜车士象全',
    category: '原本·车类',
    difficulty: 5,
    fen: '3aka3/9/2b2b3/9/9/4r4/2B6/4C4/4RA3/3AK4 w',
    winSide: 'red',
    goal: 'win',
    tip: '车炮仕相全对车士象全，实用高难局。',
  },

  // ========== 增订·马类（12，据你提供的目录） ==========
  {
    id: 'x-m-01',
    bookNo: '增一',
    title: '马兵相对高卒双士胜和两例',
    category: '增订·马类',
    difficulty: 4,
    fen: '3aka3/9/2B6/4p4/4P4/4N4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '增订：对照书中两例体会胜和分歧。',
  },
  {
    id: 'x-m-02',
    bookNo: '增二',
    title: '马底兵必胜单士象（赶象落底）',
    category: '增订·马类',
    difficulty: 3,
    fen: '3ak4/9/2b6/9/9/9/4P4/4N4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '赶象落底后底兵必胜。',
  },
  {
    id: 'x-m-03',
    bookNo: '增三',
    title: '马底兵必胜单士象（逼将上顶）',
    category: '增订·马类',
    difficulty: 3,
    fen: '4k4/4a4/2b6/9/9/9/4P4/4N4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '逼将上顶法。',
  },
  {
    id: 'x-m-04',
    bookNo: '增四',
    title: '马底兵胜单缺象（将同象一边）',
    category: '增订·马类',
    difficulty: 4,
    fen: '3aka3/9/2b6/9/9/9/4P4/4N4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '将象同侧则不和，可胜。',
  },
  {
    id: 'x-m-05',
    bookNo: '增五',
    title: '马底兵胜单缺象（士遮公头）',
    category: '增订·马类',
    difficulty: 4,
    fen: '4ka3/4a4/2b6/9/9/9/4P4/4N4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '注意士遮公头相关胜和。',
  },
  {
    id: 'x-m-06',
    bookNo: '增六',
    title: '马低兵胜单缺象',
    category: '增订·马类',
    difficulty: 4,
    fen: '3aka3/9/2b6/9/9/4P4/4N4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '低兵亦可胜单缺象。',
  },
  {
    id: 'x-m-07',
    bookNo: '增七',
    title: '马低兵胜单缺士',
    category: '增订·马类',
    difficulty: 4,
    fen: '4ka3/9/2b2b3/9/9/4P4/4N4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马低兵破单缺士。',
  },
  {
    id: 'x-m-08',
    bookNo: '增八',
    title: '马低兵胜双象「公底」士',
    category: '增订·马类',
    difficulty: 4,
    fen: '4k4/4a4/2b2b3/9/9/4P4/4N4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '针对公底士的胜法。',
  },
  {
    id: 'x-m-09',
    bookNo: '增九',
    title: '马兵双仕和单车（例一）',
    category: '增订·马类',
    difficulty: 4,
    fen: '4k4/9/9/9/4P4/4r4/4N4/4A4/4A4/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马兵双仕守单车。',
  },
  {
    id: 'x-m-10',
    bookNo: '增十',
    title: '马兵双仕巧和车（例二）',
    category: '增订·马类',
    difficulty: 4,
    fen: '4k4/9/9/4P4/9/4r4/4N4/4A4/4A4/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '另一守和阵形。',
  },
  {
    id: 'x-m-11',
    bookNo: '增十一',
    title: '马低兵仕胜老卒双士',
    category: '增订·马类',
    difficulty: 4,
    fen: '3aka3/9/9/9/4p4/4P4/4N4/4A4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '有仕助攻破老卒双士。',
  },
  {
    id: 'x-m-12',
    bookNo: '增十二',
    title: '马兵对炮双象的胜和规律',
    category: '增订·马类',
    difficulty: 4,
    fen: '4k4/9/2b2b3/9/4P4/4N4/9/4c4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书中马兵对炮双象规律。',
  },

  // ========== 增订·双马双炮类（7） ==========
  {
    id: 'x-nn-01',
    bookNo: '一',
    title: '双马必胜炮双士',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '3aka3/9/9/9/9/3N1N3/9/4c4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双马联攻，逼炮兑或塞士门入杀。',
  },
  {
    id: 'x-nn-02',
    bookNo: '二',
    title: '双马必胜马双士',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '3aka3/9/4n4/9/9/3N1N3/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '以马制马，逼兑后转马取双士。',
  },
  {
    id: 'x-nn-03',
    bookNo: '三',
    title: '双炮双相必胜双象',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '4k4/9/2b2b3/9/9/2B6/9/2C2C3/9/3K1B3 w',
    winSide: 'red',
    goal: 'win',
    tip: '双炮有双相可破双象。',
  },
  {
    id: 'x-nn-04',
    bookNo: '四',
    title: '双炮相不胜双象',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '4k4/9/2b2b3/9/9/2B6/9/2C2C3/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '仅一相时双炮难胜双象，正和形。',
  },
  {
    id: 'x-nn-05',
    bookNo: '五',
    title: '马炮有仕相必胜炮双象',
    category: '增订·双马双炮',
    difficulty: 4,
    fen: '4k4/9/2b2b3/9/9/2B6/4N4/4A4/4C4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马炮有仕相，破炮双象。',
  },
  {
    id: 'x-nn-06',
    bookNo: '六',
    title: '马炮仕相全胜马士象全',
    category: '增订·双马双炮',
    difficulty: 4,
    fen: '3aka3/9/2b1n1b2/9/9/2B6/4N4/4A1C2/4A4/3K1B3 w',
    winSide: 'red',
    goal: 'win',
    tip: '马炮仕相全对马士象全，属必胜实用局。',
  },
  {
    id: 'x-nn-07',
    bookNo: '七',
    title: '马炮必和车',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '4k4/9/9/9/4r4/9/4N4/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马炮联防可和单车；换执黑练攻破。',
  },

  // ========== 增订·兵类（2） ==========
  {
    id: 'x-p-01',
    bookNo: '一',
    title: '高底兵对双士的胜和规律',
    category: '增订·兵类',
    difficulty: 3,
    fen: '3aka3/9/9/9/4P4/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书：高兵与底兵对双士的胜和分野。',
  },
  {
    id: 'x-p-02',
    bookNo: '二',
    title: '双卒双士可和车',
    category: '增订·兵类',
    difficulty: 3,
    fen: '3aka3/9/9/4p4/4p4/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '双卒双士守和单车；红执车体验难胜，可换执黑守和。',
  },

  // ========== 增订·车类（15） ==========
  {
    id: 'x-r-01',
    bookNo: '一',
    title: '车对双马的胜和局例',
    category: '增订·车类',
    difficulty: 4,
    fen: '4k4/9/4n4/9/9/4n4/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '单车对双马：注意马位与是否必胜。',
  },
  {
    id: 'x-r-02',
    bookNo: '二',
    title: '车相仕巧胜炮双士',
    category: '增订·车类',
    difficulty: 3,
    fen: '3aka3/9/9/9/9/2B6/9/4A1R2/9/3K1c3 w',
    winSide: 'red',
    goal: 'win',
    tip: '有相仕助车破炮双士。',
  },
  {
    id: 'x-r-03',
    bookNo: '三',
    title: '车单缺象可和车马',
    category: '增订·车类',
    difficulty: 4,
    fen: '3ak4/9/2b6/9/4n4/9/4r4/4R4/9/3AKA3 w',
    winSide: 'red',
    goal: 'draw',
    tip: '车单缺象对车马，可成和。',
  },
  {
    id: 'x-r-04',
    bookNo: '四',
    title: '车仕相全（顶头边兵）可和车马卒',
    category: '增订·车类',
    difficulty: 4,
    fen: '3ak4/9/4n4/8p/9/2B6/4r4/4RA3/4A4/3K1B3 w',
    winSide: 'red',
    goal: 'draw',
    tip: '顶头边兵形，仕相全可和车马卒。',
  },
  {
    id: 'x-r-05',
    bookNo: '五',
    title: '车双相可和车边卒',
    category: '增订·车类',
    difficulty: 3,
    fen: '4k4/9/9/8p/9/2B2B3/4r4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '车双相对车边卒的守和要点。',
  },
  {
    id: 'x-r-06',
    bookNo: '六',
    title: '车兵双仕可胜马炮双士',
    category: '增订·车类',
    difficulty: 4,
    fen: '3aka3/9/4n4/9/4P4/9/4c4/4RA3/4A4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车兵双仕破马炮双士。',
  },
  {
    id: 'x-r-07',
    bookNo: '七',
    title: '车兵单缺仕胜车卒双象（边象低联不和）',
    category: '增订·车类',
    difficulty: 4,
    fen: '4k4/4a4/2b2b3/9/4P4/4p4/4r4/4RA3/9/2B1KB3 w',
    winSide: 'red',
    goal: 'win',
    tip: '边象低联则不和，红可胜。',
  },
  {
    id: 'x-r-08',
    bookNo: '八',
    title: '车马双相必胜车双士',
    category: '增订·车类',
    difficulty: 4,
    fen: '3aka3/9/9/9/9/2B2B3/4N4/4R4/4r4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车马有双相，破车双士。',
  },
  {
    id: 'x-r-09',
    bookNo: '九',
    title: '车马兵必胜车士象全（献马取士胜）',
    category: '增订·车类',
    difficulty: 5,
    fen: '3aka3/9/2b2b3/9/4P4/4N4/4r4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '典型献马取士入局。',
  },
  {
    id: 'x-r-10',
    bookNo: '十',
    title: '车马兵必胜车士象全（将门进兵胜）',
    category: '增订·车类',
    difficulty: 5,
    fen: '3aka3/9/2b2b3/9/9/4PN3/4r4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '将门进兵破士象全。',
  },
  {
    id: 'x-r-11',
    bookNo: '十一',
    title: '车马兵必胜车士象全（背士进兵胜）',
    category: '增订·车类',
    difficulty: 5,
    fen: '3aka3/9/2b2b3/4P4/9/4N4/4r4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '背士方向进兵取胜。',
  },
  {
    id: 'x-r-12',
    bookNo: '十二',
    title: '车炮仕胜车双象',
    category: '增订·车类',
    difficulty: 4,
    fen: '4k4/9/2b2b3/9/9/9/4r4/4RA3/4C4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车炮有仕破车双象。',
  },
  {
    id: 'x-r-13',
    bookNo: '十三',
    title: '车炮相胜车双象',
    category: '增订·车类',
    difficulty: 4,
    fen: '4k4/9/2b2b3/9/9/2B6/4r4/4R4/4C4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车炮有相破车双象。',
  },
  {
    id: 'x-r-14',
    bookNo: '十四',
    title: '车炮相胜车象的规律',
    category: '增订·车类',
    difficulty: 4,
    fen: '4k4/9/2b6/9/9/2B6/4r4/4R4/4C4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书中车炮相对车象的胜和规律。',
  },
  {
    id: 'x-r-15',
    bookNo: '十五',
    title: '车相反方向巧和车卒',
    category: '增订·车类',
    difficulty: 3,
    fen: '4k4/9/9/4p4/9/2B6/4r4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '相与卒分居两侧时的巧和。',
  },

  // ========== 增订·残棋基本杀法（按子类各一例） ==========
  {
    id: 'x-k-01',
    bookNo: '一',
    title: '车马冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/4n4/9/9/9/4N4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '书中车马冷着五例之一：教学形。',
  },
  {
    id: 'x-k-02',
    bookNo: '二',
    title: '车炮冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/9/9/4C4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车炮冷着典型入局。',
  },
  {
    id: 'x-k-03',
    bookNo: '三',
    title: '车兵冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/4P4/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车兵冷着逼杀。',
  },
  {
    id: 'x-k-04',
    bookNo: '四',
    title: '马炮冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/9/4N4/4C4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马炮冷着二例教学形。',
  },
  {
    id: 'x-k-05',
    bookNo: '五',
    title: '马兵冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/4P4/4N4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马兵冷着。',
  },
  {
    id: 'x-k-06',
    bookNo: '六',
    title: '马炮兵冷着',
    category: '增订·基本杀法',
    difficulty: 4,
    fen: '3ak4/4a4/9/9/4P4/4N4/4C4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马炮兵联攻冷着。',
  },
  {
    id: 'x-k-07',
    bookNo: '七',
    title: '炮兵冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/4P4/9/4C4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '炮兵冷着三例教学形。',
  },

  // ========== 增订·棋谚图解 ==========
  {
    id: 'x-y-01',
    bookNo: '一',
    title: '马逢边必死',
    category: '增订·棋谚图解',
    difficulty: 2,
    fen: '4k4/9/9/9/N8/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '边马易受困；对照棋谚二例。',
  },
  {
    id: 'x-y-02',
    bookNo: '二',
    title: '残棋炮归家',
    category: '增订·棋谚图解',
    difficulty: 2,
    fen: '3aka3/9/9/9/9/9/9/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '残局炮宜回中、回家控肋。',
  },
  {
    id: 'x-y-03',
    bookNo: '三',
    title: '有炮须留他家士',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '3aka3/9/9/9/9/9/4C4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '留对方士便于炮架杀。',
  },
  {
    id: 'x-y-04',
    bookNo: '四',
    title: '残棋最忌车头低',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '4k4/9/9/9/9/9/2R6/9/4r4/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '低车头易被动；体会车位高低。',
  },
  {
    id: 'x-y-05',
    bookNo: '五',
    title: '缺士怕双车',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '4k4/9/2b2b3/9/9/9/9/4R4/4R4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '缺士难挡双车。',
  },

  // ========== 增订·实战残局选评 ==========
  {
    id: 'x-z-01',
    bookNo: '一',
    title: '车卒能和车炮士',
    category: '增订·实战选评',
    difficulty: 4,
    fen: '3ak4/9/9/4p4/9/9/4r4/4RC3/4A4/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '实战选评：车卒守和车炮士。',
  },
  {
    id: 'x-z-02',
    bookNo: '二',
    title: '残棋炮归家',
    category: '增订·实战选评',
    difficulty: 3,
    fen: '3aka3/9/2b2b3/9/9/9/9/9/4C4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '实战中炮归家控局。',
  },
  {
    id: 'x-z-03',
    bookNo: '三',
    title: '三仙炼丹的基本杀势',
    category: '增订·实战选评',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/4P4/4P4/4P4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '三兵「炼丹」杀势与推论法。',
  },
]

export function getPuzzle(id: string): Puzzle | undefined {
  return PUZZLES.find((p) => p.id === id)
}

export function puzzlesByCategory(category: string): Puzzle[] {
  return PUZZLES.filter((p) => p.category === category)
}

export function nextPuzzleId(id: string): string | null {
  const i = PUZZLES.findIndex((p) => p.id === id)
  if (i < 0 || i >= PUZZLES.length - 1) return null
  return PUZZLES[i + 1].id
}
