export type PuzzleGoal = 'win' | 'draw'

export type Puzzle = {
  id: string
  title: string
  category: string
  /** 书中局号，便于对照纸书 */
  bookNo?: string
  difficulty: 1 | 2 | 3 | 4 | 5
  fen: string
  winSide: 'red' | 'black'
  goal: PuzzleGoal
  tip?: string
}

/**
 * 目录结构对照陈松顺《中国象棋实用残局增订本》
 * o-m-01 仍为早期自拟形；其余局 FEN 按 mydata/pages 书图录入（见 scripts/apply-book-fens.py）。
 * 增订·基本杀法 (x-k-*) 未改动。
 */
export const CATEGORIES = [
  '原本·马类',
  '原本·炮类',
  '原本·兵类',
  '原本·车类',
  '原本·实战运用',
  '增订·马类',
  '增订·双马双炮',
  '增订·兵类',
  '增订·车类',
  '增订·基本杀法',
  '增订·棋谚图解',
  '增订·实战选评',
  '增订·看杀局练心算',
] as const

export const PUZZLES: Puzzle[] = [
  // ========== 原本·马类（24） ==========
  {
    id: 'o-m-01',
    bookNo: '一',
    title: '马取单士',
    category: '原本·马类',
    difficulty: 2,
    fen: '4k4/4a4/9/9/9/9/9/4N4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '禁将、逼士，马挂角/卧槽收官。',
  },
  {
    id: 'o-m-02',
    bookNo: '二·图2',
    title: '马巧胜双士',
    category: '原本·马类',
    difficulty: 3,
    fen: '4a4/9/3ak4/9/N8/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双士粘性大，需等着与马步节奏，逼士离位。',
  },
  {
    id: 'o-m-03',
    bookNo: '三·图3',
    title: '马胜单象（将象归边负）',
    category: '原本·马类',
    difficulty: 3,
    fen: '3k5/9/2b6/8N/9/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '将象同侧归边时可胜；控象眼、赶象出宫。',
  },
  {
    id: 'o-m-04',
    bookNo: '四·图4',
    title: '马不胜单象（左将右象和）',
    category: '原本·马类',
    difficulty: 3,
    fen: '9/5k3/9/5N3/2b6/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '正和形：将象分居两侧。红执马体验为何难胜；可换执黑练守。',
  },
  {
    id: 'o-m-05',
    bookNo: '五·图5',
    title: '马取单卒（例一）',
    category: '原本·马类',
    difficulty: 2,
    fen: '9/5k3/9/2p6/9/9/9/8N/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '先禁卒升变路线，再运马捉卒或逼将。',
  },
  {
    id: 'o-m-06',
    bookNo: '六·图6',
    title: '马取单卒（例二）',
    category: '原本·马类',
    difficulty: 2,
    fen: '4k4/9/9/9/4p4/9/8N/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '卒在肋道时注意堵截，防止卒过河换势。',
  },
  {
    id: 'o-m-07',
    bookNo: '七·图7',
    title: '马和炮双士',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k1c2/9/3a1a3/2N6/9/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马对炮双士多为正和；体验炮士联防。',
  },
  {
    id: 'o-m-08',
    bookNo: '八·图8',
    title: '马巧和炮卒双士',
    category: '原本·马类',
    difficulty: 4,
    fen: '4c4/4a4/2Nk1a3/9/4p4/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '多卒时仍有巧和可能，重在兑子与占位。',
  },
  {
    id: 'o-m-09',
    bookNo: '九·图9',
    title: '马当仕和车',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/9/9/9/6r2/9/9/3N5/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马占仕位顶车，经典守和思路。',
  },
  {
    id: 'o-m-10',
    bookNo: '十·图10',
    title: '马当相和车',
    category: '原本·马类',
    difficulty: 3,
    fen: '5k3/9/9/4N4/9/6r2/9/9/9/2BK5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马占相位支应，防车切入。',
  },
  {
    id: 'o-m-11',
    bookNo: '十一·图11',
    title: '马双相和车（高相可和）',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/2B2B3/4N4/9/7r1/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '高相连环可和单车。',
  },
  {
    id: 'o-m-12',
    bookNo: '十二·图12',
    title: '马双象不和车（低象不和）',
    category: '原本·马类',
    difficulty: 3,
    // 执车方（红）破低象马
    fen: '4k4/9/9/4n4/2b1b4/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对方低象时，单车可破马双象。',
  },
  {
    id: 'o-m-13',
    bookNo: '十三·图13',
    title: '马兵相巧和车',
    category: '原本·马类',
    difficulty: 4,
    fen: '4k4/9/9/9/6b2/6N2/4P1r2/4B4/4K4/9 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马兵相联防顶车，注意兵勿乱进。',
  },
  {
    id: 'o-m-14',
    bookNo: '十四·图14',
    title: '马低卒不胜双仕兵',
    category: '原本·马类',
    difficulty: 3,
    fen: '9/3k5/9/2n6/9/9/1P7/5p3/3A1A3/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '红有双仕兵守马低卒，多为不胜/和形。',
  },
  {
    id: 'o-m-15',
    bookNo: '十五·图15',
    title: '马兵巧胜士象全',
    category: '原本·马类',
    difficulty: 4,
    fen: '2bak4/4aP3/4b4/9/2N6/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '高难度巧胜：运马赶象、借兵破士。',
  },
  {
    id: 'o-m-16',
    bookNo: '十六·图16',
    title: '马卒不胜仕相全（正和局）',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/9/9/5p3/4n4/9/2B3B2/3A1A3/4K4 w',
    winSide: 'black',
    goal: 'draw',
    tip: '执黑马卒攻红仕相全：体会正和。',
  },
  {
    id: 'o-m-17',
    bookNo: '十七·图17',
    title: '马低卒不胜单缺仕',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/9/9/7n1/9/9/4Bp2B/3K5/4A4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '红守单缺仕，马低卒难胜。',
  },
  {
    id: 'o-m-18',
    bookNo: '十八·图18',
    title: '马低卒不胜单缺相',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/9/9/9/3p5/9/1n7/4AK3/2B2A3 w',
    winSide: 'red',
    goal: 'draw',
    tip: '双仕单相守和：帅相分左右、露公头，相宜边上飞；首着相七退九。勿走相五进三致欠行。',
  },
  {
    id: 'o-m-19',
    bookNo: '十九·图19',
    title: '马高兵必胜单缺象',
    category: '原本·马类',
    difficulty: 4,
    fen: '5k3/4a4/b2aP4/5N3/9/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '高兵到位则必胜单缺象，先定中再破士。',
  },
  {
    id: 'o-m-20',
    bookNo: '二十·图20',
    title: '马兵胜炮象',
    category: '原本·马类',
    difficulty: 3,
    fen: '3k5/4P4/2c6/2N6/6b2/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '马兵配合捉炮或逼象，形成杀势。',
  },
  {
    id: 'o-m-21',
    bookNo: '二十一·图21',
    title: '马低卒不胜单炮',
    category: '原本·马类',
    difficulty: 3,
    fen: '4k4/9/9/9/4C4/9/7n1/3K5/4p4/9 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单炮可顶马低卒，红方体会守和。',
  },
  {
    id: 'o-m-22',
    bookNo: '二十二·图22',
    title: '马高兵单相巧胜马士',
    category: '原本·马类',
    difficulty: 4,
    fen: '3ak4/9/2N1P1n2/9/9/9/9/4B4/5K3/9 w',
    winSide: 'red',
    goal: 'win',
    tip: '有相助攻，借高兵兑子入局。',
  },
  {
    id: 'o-m-23',
    bookNo: '二十三·图23',
    title: '马高兵必胜炮士',
    category: '原本·马类',
    difficulty: 3,
    fen: '4ka3/c8/4P4/5N3/9/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '高兵禁炮，马士配合得子或杀。',
  },
  {
    id: 'o-m-24',
    bookNo: '二十四·图24',
    title: '马兵（未过河）胜双象',
    category: '原本·马类',
    difficulty: 4,
    fen: '3k5/9/4b3b/9/3N2P2/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '兵未过河仍可胜双象，关键在控象与推进时机。',
  },

  // ========== 原本·炮类（16） ==========
  {
    id: 'o-c-25',
    bookNo: '二十五·图25',
    title: '炮仕胜双士',
    category: '原本·炮类',
    difficulty: 2,
    fen: '5k3/4a4/3a5/9/9/9/9/5A3/1C7/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '有仕作炮架，破双士。',
  },
  {
    id: 'o-c-26',
    bookNo: '二十六·图26',
    title: '炮士象全不胜单仕相',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/5c3/b2a1a3/9/2b6/9/9/3A4B/3K5/9 w',
    winSide: 'black',
    goal: 'draw',
    tip: '执黑炮士象全攻红单仕相：体会不胜。',
  },
  {
    id: 'o-c-27',
    bookNo: '二十七·图27',
    title: '炮双仕和车',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/9/9/9/7r1/9/5C3/4A4/3K1A3 w',
    winSide: 'red',
    goal: 'draw',
    tip: '炮双仕顶车正和。',
  },
  {
    id: 'o-c-28',
    bookNo: '二十八·图28',
    title: '炮双相和车（低相可和）',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/9/9/9/4C2r1/9/4B4/9/2B1K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '低相形可和单车。',
  },
  {
    id: 'o-c-29',
    bookNo: '二十九·图29',
    title: '炮双象不和车（高象不和）',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/4b4/7R1/2b1c4/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '执车破高象炮双象。',
  },
  {
    id: 'o-c-30',
    bookNo: '三十·图30',
    title: '炮双仕必和三高卒',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/9/2p1p1p2/9/9/9/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '炮双仕守三高卒。',
  },
  {
    id: 'o-c-31',
    bookNo: '三十一·图31',
    title: '炮仕相全和车卒',
    category: '原本·炮类',
    difficulty: 4,
    fen: '4k4/9/9/9/9/9/2rp5/3B5/3A5/1B1KC4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '全士相炮守车卒。',
  },
  {
    id: 'o-c-32',
    bookNo: '三十二·图32',
    title: '炮巧和炮卒士',
    category: '原本·炮类',
    difficulty: 4,
    fen: '5c3/4a4/4k3c/9/9/9/9/5K3/4p4/7C1 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单炮巧和炮卒士。',
  },
  {
    id: 'o-c-33',
    bookNo: '三十三·图33',
    title: '炮低兵禁单象（将上顶不和）',
    category: '原本·炮类',
    difficulty: 3,
    fen: '9/5P3/4kb3/9/9/9/9/5K3/9/7C1 w',
    winSide: 'red',
    goal: 'win',
    tip: '低兵禁象，逼将上顶可胜。',
  },
  {
    id: 'o-c-34',
    bookNo: '三十四·图34',
    title: '炮低卒象不胜单相（巧和）',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/2b6/9/4p4/4c4/2B6/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单相巧和炮低卒象。',
  },
  {
    id: 'o-c-35',
    bookNo: '三十五·图35',
    title: '炮高兵必胜单象',
    category: '原本·炮类',
    difficulty: 3,
    fen: '4k4/9/2b6/9/4P4/9/9/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '高兵作架或逼宫，必胜单象。',
  },
  {
    id: 'o-c-36',
    bookNo: '三十六·图36',
    title: '炮底兵仕相必胜单士象',
    category: '原本·炮类',
    difficulty: 4,
    fen: '3ak4/9/2b6/9/9/9/4P4/4C4/4A4/3KB4 w',
    winSide: 'red',
    goal: 'win',
    tip: '底兵配合仕相炮，破单士象。',
  },
  {
    id: 'o-c-37',
    bookNo: '三十七·图37',
    title: '炮底兵仕对单士象的胜和规律',
    category: '原本·炮类',
    difficulty: 4,
    fen: '3ak4/9/2b6/9/9/9/4P4/4C4/4A4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书中规律：仕位相、将位决定胜和。',
  },
  {
    id: 'o-c-38',
    bookNo: '三十八·图38',
    title: '炮双过河兵可和车',
    category: '原本·炮类',
    difficulty: 4,
    fen: '4k4/9/9/2P2P3/9/4r4/9/4C4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '双过河兵+炮顶车。',
  },
  {
    id: 'o-c-39',
    bookNo: '三十九·图39',
    title: '炮兵仕相全胜士象全（沉炮法）',
    category: '原本·炮类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/9/4P4/9/2B6/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'win',
    tip: '例一：沉底炮法破士象全。',
  },
  {
    id: 'o-c-40',
    bookNo: '四十·图40',
    title: '炮兵仕相全胜士象全（破羊角士）',
    category: '原本·炮类',
    difficulty: 5,
    fen: '4ka3/3a5/2b2b3/9/4P4/9/2B6/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'win',
    tip: '例二：针对羊角士的破法。',
  },

  // ========== 原本·兵类（11） ==========
  {
    id: 'o-p-41',
    bookNo: '四十一·图41',
    title: '一兵单相巧胜单士',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3ak4/9/9/9/4P4/9/2B6/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '兵相配合巧胜单士。',
  },
  {
    id: 'o-p-42',
    bookNo: '四十二·图42',
    title: '单兵和炮士象',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3ak4/9/2b6/9/4P4/9/9/4c4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单兵难破炮士象，多为和。',
  },
  {
    id: 'o-p-43',
    bookNo: '四十三·图43',
    title: '兵仕巧和双卒双士',
    category: '原本·兵类',
    difficulty: 4,
    fen: '3aka3/9/9/2p2p3/9/9/4P4/4A4/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '兵仕巧守双卒双士。',
  },
  {
    id: 'o-p-44',
    bookNo: '四十四·图44',
    title: '双兵巧胜单缺象',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3aka3/9/2b6/9/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双兵联手破单缺象。',
  },
  {
    id: 'o-p-45',
    bookNo: '四十五·图45',
    title: '双兵巧胜单缺士',
    category: '原本·兵类',
    difficulty: 3,
    fen: '4ka3/9/2b2b3/9/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双兵破单缺士。',
  },
  {
    id: 'o-p-46',
    bookNo: '四十六·图46',
    title: '双兵巧胜士象全',
    category: '原本·兵类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/9/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双兵巧胜士象全，重在联兵与塞象眼。',
  },
  {
    id: 'o-p-47',
    bookNo: '四十七·图47',
    title: '双兵不胜单士象',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3ak4/9/2b6/9/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'draw',
    tip: '单士象可顶双兵。',
  },
  {
    id: 'o-p-48',
    bookNo: '四十八·图48',
    title: '双兵对单卒象',
    category: '原本·兵类',
    difficulty: 3,
    fen: '4k4/9/2b6/4p4/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书中胜和分支练习。',
  },
  {
    id: 'o-p-49',
    bookNo: '四十九·图49',
    title: '双兵对单卒士',
    category: '原本·兵类',
    difficulty: 3,
    fen: '3ak4/9/9/4p4/3P1P3/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '双兵对卒士，注意兑兵时机。',
  },
  {
    id: 'o-p-50',
    bookNo: '五十·图50',
    title: '三兵胜士象全（例一）',
    category: '原本·兵类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/9/2P1P1P2/9/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '三兵例胜士象全。',
  },
  {
    id: 'o-p-51',
    bookNo: '五十一·图51',
    title: '三兵胜士象全（例二）',
    category: '原本·兵类',
    difficulty: 4,
    fen: '3k1a3/5a3/2b2b3/9/3P1P3/6P2/9/9/9/5K3 w',
    winSide: 'red',
    goal: 'win',
    tip: '三兵另一典型阵形。',
  },

  // ========== 原本·车类（19） ==========
  {
    id: 'o-r-52',
    bookNo: '五十二·图52',
    title: '车不胜仕相全（正和局）',
    category: '原本·车类',
    difficulty: 2,
    fen: '4k4/9/9/9/9/9/6r2/4B4/4A4/4KAB2 w',
    winSide: 'black',
    goal: 'draw',
    tip: '执黑单车攻仕相全：正和，体验守方联防。',
  },
  {
    id: 'o-r-53',
    bookNo: '五十三·图53',
    title: '车巧胜士象全（例一）',
    category: '原本·车类',
    difficulty: 4,
    fen: '3k1ab2/4a4/8b/9/9/9/9/9/4K4/8R w',
    winSide: 'red',
    goal: 'win',
    tip: '单车巧胜士象全，需精确控肋。',
  },
  {
    id: 'o-r-54',
    bookNo: '五十四·图54',
    title: '车巧胜士象全（例二）',
    category: '原本·车类',
    difficulty: 4,
    fen: '3a5/5k3/2R1ba3/9/2b6/9/9/9/4K4/9 w',
    winSide: 'red',
    goal: 'win',
    tip: '另一典型入局次序。',
  },
  {
    id: 'o-r-55',
    bookNo: '五十五·图55',
    title: '车必胜马双士（例一）',
    category: '原本·车类',
    difficulty: 3,
    fen: '4ka3/4an3/9/3R5/9/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '车必胜马双士。',
  },
  {
    id: 'o-r-56',
    bookNo: '五十六·图56',
    title: '车必胜马双士（例二）',
    category: '原本·车类',
    difficulty: 3,
    fen: '4ak3/5a3/3n5/6R2/9/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '马位不同时的必胜法。',
  },
  {
    id: 'o-r-57',
    bookNo: '五十七·图57',
    title: '车炮胜单车（车正则胜）',
    category: '原本·车类',
    difficulty: 4,
    fen: '5k3/9/5r3/9/9/2C1R4/9/9/4K4/9 w',
    winSide: 'red',
    goal: 'win',
    tip: '车占中肋则车炮必胜单车。',
  },
  {
    id: 'o-r-58',
    bookNo: '五十八·图58',
    title: '车炮胜单车（迫车离中胜）',
    category: '原本·车类',
    difficulty: 4,
    fen: '5k3/9/9/9/4C4/4r2R1/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '先迫对方车离中，再入局。',
  },
  {
    id: 'o-r-59',
    bookNo: '五十九·图59',
    title: '车底兵胜单车（车正则胜）',
    category: '原本·车类',
    difficulty: 4,
    fen: '3P5/5k3/9/9/5r3/4R4/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '底兵+中车胜单车。',
  },
  {
    id: 'o-r-60',
    bookNo: '六十·图60',
    title: '车低兵仕胜车士（士遮头不和）',
    category: '原本·车类',
    difficulty: 4,
    fen: '5k3/3Pra3/9/9/9/9/9/3A1R3/4K4/9 w',
    winSide: 'red',
    goal: 'win',
    tip: '破单车保士：士遮头则不和。',
  },
  {
    id: 'o-r-61',
    bookNo: '六十一·图61',
    title: '车仕和车低卒（单车保剑）',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/4a4/4r4/9/9/9/9/3R1A3/3K1p3/9 w',
    winSide: 'red',
    goal: 'draw',
    tip: '又名「单车保剑」：车仕守车低卒。',
  },
  {
    id: 'o-r-62',
    bookNo: '六十二·图62',
    title: '车仕相全和车双卒',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/2B6/2p2p3/9/4r4/9/4R4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '全士相车守车双卒。',
  },
  {
    id: 'o-r-63',
    bookNo: '六十三·图63',
    title: '车双兵巧胜车士象全',
    category: '原本·车类',
    difficulty: 5,
    fen: '3aka3/9/2b2b3/9/3P1P3/4r4/9/4R4/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '车双兵对车士象全，高难度巧胜。',
  },
  {
    id: 'o-r-64',
    bookNo: '六十四·图64',
    title: '车相和车卒（相在卒一边和）',
    category: '原本·车类',
    difficulty: 3,
    fen: '4k4/9/2B6/4p4/9/4r4/9/4R4/9/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '相与卒同侧可和。',
  },
  {
    id: 'o-r-65',
    bookNo: '六十五·图65',
    title: '车兵胜车象（象不在兵一边不和）',
    category: '原本·车类',
    difficulty: 3,
    fen: '4k4/9/6b2/9/4P4/4r4/9/4R4/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '象不在兵一侧时可胜。',
  },
  {
    id: 'o-r-66',
    bookNo: '六十六·图66',
    title: '车兵有仕相必胜车双象',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/2b2b3/9/4P4/4r4/2B6/4R4/4A4/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '有仕相则车兵必胜车双象。',
  },
  {
    id: 'o-r-67',
    bookNo: '六十七·图67',
    title: '车高兵必胜双卒士象全',
    category: '原本·车类',
    difficulty: 4,
    fen: '3aka3/9/2b2b3/2p2p3/4P4/9/9/4R4/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '车高兵破双卒士象全。',
  },
  {
    id: 'o-r-68',
    bookNo: '六十八·图68',
    title: '车炮双仕必和双车',
    category: '原本·车类',
    difficulty: 4,
    fen: '4k4/9/9/9/9/3r1r3/9/4C4/4A4/3AK4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '车炮双仕守双车。',
  },
  {
    id: 'o-r-69',
    bookNo: '六十九·图69',
    title: '双车双相巧胜车炮双士',
    category: '原本·车类',
    difficulty: 5,
    fen: '3aka3/9/9/9/9/4r4/2B2B3/4c4/3R1R3/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '双车双相攻车炮双士。',
  },
  {
    id: 'o-r-70',
    bookNo: '七十·图70',
    title: '车炮仕相全巧胜车士象全',
    category: '原本·车类',
    difficulty: 5,
    fen: '3aka3/9/2b3b2/9/9/7r1/2B6/4C4/4RA3/3AK4 w',
    winSide: 'red',
    goal: 'win',
    tip: '车炮仕相全对车士象全，实用高难局。',
  },

  // ========== 原本·实战运用（6例+2测验） ==========
  {
    id: 'o-pr-01',
    bookNo: '例一·图71',
    title: '兑车转马巧胜双士',
    category: '原本·实战运用',
    difficulty: 4,
    fen: '4ka3/3a3r1/9/9/9/9/7Np/9/7R1/4KA3 w',
    winSide: 'red',
    goal: 'win',
    tip: '勿按「单马难胜双士」常规兑马；兑车后马进九、马进八可巧胜。',
  },
  {
    id: 'o-pr-02',
    bookNo: '例二·图72',
    title: '兑车得马胜单士',
    category: '原本·实战运用',
    difficulty: 4,
    fen: '4a4/4k4/9/6p2/3Nnr3/4N2R1/9/9/9/4K1B2 w',
    winSide: 'red',
    goal: 'win',
    tip: '危局中求胜：车八平六兑车，马五进三再马五退六，得马后成马胜单士。',
  },
  {
    id: 'o-pr-03',
    bookNo: '例三·图73',
    title: '仕六退五巧胜单象',
    category: '原本·实战运用',
    difficulty: 4,
    fen: '5k3/9/9/4r4/b8/4N4/4R4/9/5A3/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '兑车前先仕六退五，使象不能飞中，再车四退三、马四退六胜。',
  },
  {
    id: 'o-pr-04',
    bookNo: '例四·图74',
    title: '兑子成车马炮例胜',
    category: '原本·实战运用',
    difficulty: 4,
    fen: '3aka3/9/4c4/9/9/9/r8/4N4/3pR4/4KA2C w',
    winSide: 'red',
    goal: 'win',
    tip: '车五进二兑车，炮一平五，帅六进一，成例胜残局。',
  },
  {
    id: 'o-pr-05',
    bookNo: '例五·图75',
    title: '花心取蜜成车兵相胜',
    category: '原本·实战运用',
    difficulty: 5,
    fen: '1b2k4/3a5/3ra4/8b/7P1/3r5/9/RR6B/3A5/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车三进七、帅五平四，用车兵相「花心取蜜」走成车兵相必胜车双象。',
  },
  {
    id: 'o-pr-06',
    bookNo: '例六·图76',
    title: '兑车双兵步数胜卒象',
    category: '原本·实战运用',
    difficulty: 4,
    fen: '9/9/4k4/3b5/3p5/9/5P2P/7P1/r6R1/3K5 b',
    winSide: 'red',
    goal: 'win',
    tip: '黑先车8平5；红应兑车并算清双兵对卒象步数，兵三进一献兵是关键。',
  },
  {
    id: 'o-pr-07',
    bookNo: '测验·图77',
    title: '测验局一（红先胜）',
    category: '原本·实战运用',
    difficulty: 4,
    fen: '1PP1k1P2/2a1a4/7b1/5b1P1/9/9/8p/8P/3C1R3/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '运用攻击战术制造例胜残局；参看本书兵类及前述例局。',
  },
  {
    id: 'o-pr-08',
    bookNo: '测验·图78',
    title: '测验局二（红先和）',
    category: '原本·实战运用',
    difficulty: 4,
    fen: '3akb3/4a4/7r1/8c/9/6B2/9/1P2p2B1/N3r4/3KA4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '下风求和，利用例和残局迅速摆脱；参看本书马类残局。',
  },

  // ========== 增订·马类（13，据增订本目录） ==========
  {
    id: 'x-m-01',
    bookNo: '图1',
    title: '马兵相对高卒双士（红胜）',
    category: '增订·马类',
    difficulty: 4,
    fen: '3ak4/9/5a3/9/9/7p1/2N6/4P4/9/4K1B2 w',
    winSide: 'red',
    goal: 'win',
    tip: '增订图1：高卒双士形，红先可胜。',
  },
  {
    id: 'x-m-02',
    bookNo: '图2',
    title: '马兵相对高卒双士（和）',
    category: '增订·马类',
    difficulty: 4,
    fen: '9/4ak3/6a2/9/9/5p3/1N7/4P4/9/4KB3 w',
    winSide: 'red',
    goal: 'draw',
    tip: '增订图2：卒位不同成和；对照图1体会胜和分歧。',
  },
  {
    id: 'x-m-03',
    bookNo: '增三·图3',
    title: '马底兵必胜单士象（赶象落底）',
    category: '增订·马类',
    difficulty: 3,
    fen: '4k4/3a5/2b6/9/9/9/4N4/5P3/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '赶象落底后底兵必胜。',
  },
  {
    id: 'x-m-04',
    bookNo: '增四·图5',
    title: '马底兵必胜单士象（逼将上顶）',
    category: '增订·马类',
    difficulty: 3,
    fen: '4k4/3a1a3/2b6/9/9/9/4N4/6P2/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '逼将上顶法。',
  },
  {
    id: 'x-m-05',
    bookNo: '增五·图6',
    title: '马底兵胜单缺象（将同象一边）',
    category: '增订·马类',
    difficulty: 4,
    fen: '3a5/4k4/2b6/9/9/9/4N4/4P4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '将象同侧则不和，可胜。',
  },
  {
    id: 'x-m-06',
    bookNo: '增六·图7',
    title: '马底兵胜单缺象（士遮公头）',
    category: '增订·马类',
    difficulty: 4,
    fen: '4k4/3a5/2b6/9/4P4/9/4N4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '注意士遮公头相关胜和。',
  },
  {
    id: 'x-m-07',
    bookNo: '增七·图8',
    title: '马低兵胜单缺象',
    category: '增订·马类',
    difficulty: 4,
    fen: '3k5/4aP3/5a3/2b6/9/9/4N4/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '低兵亦可胜单缺象。',
  },
  {
    id: 'x-m-08',
    bookNo: '增八·图9',
    title: '马低兵胜单缺士',
    category: '增订·马类',
    difficulty: 4,
    fen: '5a3/3k1P3/4b4/9/1Nb6/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '马低兵破单缺士。',
  },
  {
    id: 'x-m-09',
    bookNo: '增九·图10',
    title: '马低兵胜双象「公底」士',
    category: '增订·马类',
    difficulty: 4,
    fen: '4a4/3k1P3/8b/6b2/5N3/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '针对公底士的胜法。',
  },
  {
    id: 'x-m-10',
    bookNo: '增十·图11',
    title: '马兵双仕和单车（例一）',
    category: '增订·马类',
    difficulty: 4,
    fen: '4ka3/9/9/9/4P4/r8/9/4NA3/4A4/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马兵双仕守单车。',
  },
  {
    id: 'x-m-11',
    bookNo: '增十一·图12',
    title: '马兵双仕巧和车（例二）',
    category: '增订·马类',
    difficulty: 4,
    fen: '2bk1a3/9/9/2P2N3/9/3r5/9/9/3A5/4KA3 w',
    winSide: 'red',
    goal: 'draw',
    tip: '另一守和阵形。',
  },
  {
    id: 'x-m-12',
    bookNo: '增十二·图13',
    title: '马低兵仕胜老卒双士',
    category: '增订·马类',
    difficulty: 4,
    fen: '4ak3/6P2/4a4/7N1/9/9/9/9/5A3/4K2p1 w',
    winSide: 'red',
    goal: 'win',
    tip: '有仕助攻破老卒双士。',
  },
  {
    id: 'x-m-13',
    bookNo: '增十三·图14',
    title: '马兵对炮双象的胜和规律',
    category: '增订·马类',
    difficulty: 4,
    fen: '3bk4/4P4/4b3c/N8/9/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书中马兵对炮双象规律。',
  },

  // ========== 增订·双马双炮类（7） ==========
  {
    id: 'x-nn-01',
    bookNo: '一·图15',
    title: '双马必胜炮双士',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '4k4/4a2c1/5a3/9/9/1N5N1/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '双马联攻，逼炮兑或塞士门入杀。',
  },
  {
    id: 'x-nn-02',
    bookNo: '二·图16',
    title: '双马必胜马双士',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '4k4/4a4/5a2n/3N5/9/5N3/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '以马制马，逼兑后转马取双士。',
  },
  {
    id: 'x-nn-03',
    bookNo: '三·图17',
    title: '双炮双相必胜双象',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '3k5/9/4b4/6b2/9/9/2B3B2/9/4K4/4CC3 w',
    winSide: 'red',
    goal: 'win',
    tip: '双炮有双相可破双象。',
  },
  {
    id: 'x-nn-04',
    bookNo: '四·图18',
    title: '双炮相不胜双象',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '3k5/9/4b4/6b2/9/9/6B2/9/4K4/4CC3 w',
    winSide: 'red',
    goal: 'draw',
    tip: '仅一相时双炮难胜双象，正和形。',
  },
  {
    id: 'x-nn-05',
    bookNo: '五·图19',
    title: '马炮有仕相必胜炮双象',
    category: '增订·双马双炮',
    difficulty: 4,
    fen: '4k4/6c2/4b1n2/9/9/2B6/9/3K1A2B/4C4/9 w',
    winSide: 'red',
    goal: 'win',
    tip: '马炮有仕相，破炮双象。',
  },
  {
    id: 'x-nn-06',
    bookNo: '六·图21',
    title: '马炮仕相全胜马士象全',
    category: '增订·双马双炮',
    difficulty: 4,
    fen: '4akb2/5aN2/5b3/9/7n1/9/6B2/B2A1A3/4K4/6C2 w',
    winSide: 'red',
    goal: 'win',
    tip: '马炮仕相全对马士象全，属必胜实用局。',
  },
  {
    id: 'x-nn-07',
    bookNo: '七·图22',
    title: '马炮必和车',
    category: '增订·双马双炮',
    difficulty: 3,
    fen: '5c3/5k3/9/2R6/3n5/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '马炮联防可和单车；换执黑练攻破。',
  },

  // ========== 增订·兵类（2） ==========
  {
    id: 'x-p-01',
    bookNo: '一·图23',
    title: '高底兵对双士的胜和规律',
    category: '增订·兵类',
    difficulty: 3,
    fen: '4k3P/4a4/5a3/4P4/9/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书：高兵与底兵对双士的胜和分野。',
  },
  {
    id: 'x-p-02',
    bookNo: '二·图24',
    title: '双卒双士可和车',
    category: '增订·兵类',
    difficulty: 3,
    fen: '3aka3/9/9/9/2R6/4pp3/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '双卒双士守和单车；红执车体验难胜，可换执黑守和。',
  },

  // ========== 增订·车类（15） ==========
  {
    id: 'x-r-01',
    bookNo: '一·图25',
    title: '车对双马的胜和局例',
    category: '增订·车类',
    difficulty: 4,
    fen: '5k3/9/5n3/9/3nR4/9/9/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '单车对双马：注意马位与是否必胜。',
  },
  {
    id: 'x-r-02',
    bookNo: '二·图28',
    title: '车相仕巧胜炮双士',
    category: '增订·车类',
    difficulty: 3,
    fen: '4ka3/4a4/9/9/9/7B1/8R/6A2/5K2c/9 w',
    winSide: 'red',
    goal: 'win',
    tip: '有相仕助车破炮双士。',
  },
  {
    id: 'x-r-03',
    bookNo: '三·图29',
    title: '车单缺象可和车马',
    category: '增订·车类',
    difficulty: 4,
    fen: '3ak4/9/1Rb3r2/7n1/9/9/9/9/9/3AKAB2 w',
    winSide: 'red',
    goal: 'draw',
    tip: '车单缺象对车马，可成和。',
  },
  {
    id: 'x-r-04',
    bookNo: '四·图30',
    title: '车仕相全（顶头边兵）可和车马卒',
    category: '增订·车类',
    difficulty: 4,
    fen: '3baka2/9/5b3/9/9/pn7/9/P6R1/r2BA4/4KAB2 w',
    winSide: 'red',
    goal: 'draw',
    tip: '顶头边兵形，仕相全可和车马卒。',
  },
  {
    id: 'x-r-05',
    bookNo: '五·图32',
    title: '车双相可和车边卒',
    category: '增订·车类',
    difficulty: 3,
    fen: '3a1k3/3ab4/4r4/9/9/1p7/9/7R1/4B4/2B1K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '车双相对车边卒的守和要点。',
  },
  {
    id: 'x-r-06',
    bookNo: '六·图33',
    title: '车兵双仕可胜马炮双士',
    category: '增订·车类',
    difficulty: 4,
    fen: '3a5/4ak3/3n1c3/P4R3/9/9/9/4A4/9/4AK3 w',
    winSide: 'red',
    goal: 'win',
    tip: '车兵双仕破马炮双士。',
  },
  {
    id: 'x-r-07',
    bookNo: '七·图35',
    title: '车兵单缺仕胜车卒双象（边象低联不和）',
    category: '增订·车类',
    difficulty: 4,
    fen: '6b2/5P3/3k4b/R8/9/3pr4/9/8B/4A4/4K1B2 w',
    winSide: 'red',
    goal: 'win',
    tip: '边象低联则不和，红可胜。',
  },
  {
    id: 'x-r-08',
    bookNo: '八·图37',
    title: '车马双相必胜车双士',
    category: '增订·车类',
    difficulty: 4,
    fen: '3aka3/9/2B3B2/9/2N6/3R5/3r5/9/9/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '车马有双相，破车双士。',
  },
  {
    id: 'x-r-09',
    bookNo: '九·图38',
    title: '车马兵必胜车士象全（献马取士胜）',
    category: '增订·车类',
    difficulty: 5,
    fen: '3ak1b2/4a4/1r7/3P4b/4NR3/6B2/9/4B4/9/5K3 w',
    winSide: 'red',
    goal: 'win',
    tip: '典型献马取士入局。',
  },
  {
    id: 'x-r-10',
    bookNo: '十·图39',
    title: '车马兵必胜车士象全（将门进兵胜）',
    category: '增订·车类',
    difficulty: 5,
    fen: '2bk1a3/4a4/b2r5/1P3R3/9/7N1/9/5A2B/4A4/4K1B2 w',
    winSide: 'red',
    goal: 'win',
    tip: '将门进兵破士象全。',
  },
  {
    id: 'x-r-11',
    bookNo: '十一·图40',
    title: '车马兵必胜车士象全（背士进兵胜）',
    category: '增订·车类',
    difficulty: 5,
    fen: '3aka3/9/4bb3/9/2P6/1r5N1/6R2/9/4A4/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '背士方向进兵取胜。',
  },
  {
    id: 'x-r-12',
    bookNo: '十二·图42',
    title: '车炮仕胜车双象',
    category: '增订·车类',
    difficulty: 4,
    fen: '4k4/9/2b3b2/9/3R5/4r4/9/5A3/4C4/5K3 w',
    winSide: 'red',
    goal: 'win',
    tip: '车炮有仕破车双象。',
  },
  {
    id: 'x-r-13',
    bookNo: '十三·图44',
    title: '车炮相胜车双象',
    category: '增订·车类',
    difficulty: 4,
    fen: '4k4/4R4/4bb3/9/9/4r4/9/9/9/2B1CK3 w',
    winSide: 'red',
    goal: 'win',
    tip: '车炮有相破车双象。',
  },
  {
    id: 'x-r-14',
    bookNo: '十四·图45',
    title: '车炮相胜车象的规律',
    category: '增订·车类',
    difficulty: 4,
    fen: '3k5/9/4b4/9/9/3r5/9/4R4/9/2C1K1B2 w',
    winSide: 'red',
    goal: 'win',
    tip: '对照书中车炮相对车象的胜和规律。',
  },
  {
    id: 'x-r-15',
    bookNo: '十五·图49',
    title: '车相反方向巧和车卒',
    category: '增订·车类',
    difficulty: 3,
    fen: '5k3/9/9/1p7/4R4/5r3/9/9/9/B3K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '相与卒分居两侧时的巧和。',
  },

  // ========== 增订·残棋基本杀法（按子类各一例） ==========
  {
    id: 'x-k-01',
    bookNo: '一',
    title: '车马冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/4n4/9/9/9/4N4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '书中车马冷着五例之一：教学形。',
  },
  {
    id: 'x-k-02',
    bookNo: '二',
    title: '车炮冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/9/9/4C4/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车炮冷着典型入局。',
  },
  {
    id: 'x-k-03',
    bookNo: '三',
    title: '车兵冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/4P4/9/9/4R4/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '车兵冷着逼杀。',
  },
  {
    id: 'x-k-04',
    bookNo: '四',
    title: '马炮冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/9/4N4/4C4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马炮冷着二例教学形。',
  },
  {
    id: 'x-k-05',
    bookNo: '五',
    title: '马兵冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/4P4/4N4/9/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马兵冷着。',
  },
  {
    id: 'x-k-06',
    bookNo: '六',
    title: '马炮兵冷着',
    category: '增订·基本杀法',
    difficulty: 4,
    fen: '3ak4/4a4/9/9/4P4/4N4/4C4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '马炮兵联攻冷着。',
  },
  {
    id: 'x-k-07',
    bookNo: '七',
    title: '炮兵冷着',
    category: '增订·基本杀法',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/4P4/9/4C4/9/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '炮兵冷着三例教学形。',
  },

  // ========== 增订·棋谚图解（12例） ==========
  {
    id: 'x-y-01',
    bookNo: '一·例一·图78',
    title: '马逢边必死',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '3b1k2N/3na4/3ab4/9/9/8n/9/9/3AB4/2B1K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '边马无出路；马一退二、马二退四后黑边马必死。',
  },
  {
    id: 'x-y-02',
    bookNo: '一·例二·图79',
    title: '马逢边必死（双马缺士）',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '3b1k3/4a4/3ab4/8N/5n3/3N5/9/9/4A4/2B1KB3 w',
    winSide: 'red',
    goal: 'win',
    tip: '单马对双马单缺士，马不在边也可被赶至边线困死。',
  },
  {
    id: 'x-y-03',
    bookNo: '二·例一·图80',
    title: '残棋炮归家（胜）',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '4k4/5a3/9/9/9/5r3/9/9/9/4K1CN1 w',
    winSide: 'red',
    goal: 'win',
    tip: '炮三退八、炮三平四归家，缚住黑车再运马禁将。',
  },
  {
    id: 'x-y-04',
    bookNo: '二·例二·图81',
    title: '残棋炮归家（和）',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '4k4/9/9/4C3P/9/9/7r1/9/5A3/4K1B2 w',
    winSide: 'red',
    goal: 'draw',
    tip: '炮七退三、炮七平五归家，黑车不敢离中线，和棋。',
  },
  {
    id: 'x-y-05',
    bookNo: '三·例一·图82',
    title: '有炮须留他家士（古局）',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '3ak4/4a4/9/9/7C1/p8/8b/9/5P3/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '炮八进六、兵三进一，利用黑双士为炮架巧胜。',
  },
  {
    id: 'x-y-06',
    bookNo: '三·例二·图83',
    title: '有炮须留他家士（勿吃士）',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '3aka3/9/9/5C3/6bc1/9/9/9/4P4/5K3 w',
    winSide: 'red',
    goal: 'win',
    tip: '红炮勿吃士，留士为架；炮五进一连续进炮胜。',
  },
  {
    id: 'x-y-07',
    bookNo: '三·例三·图84',
    title: '有炮须留他家士（禁制）',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '2aka4/9/9/9/6C2/6C2/3C5/3B5/9/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '进炮叫将吃士不能赢；炮二平五后用禁制战术胜。',
  },
  {
    id: 'x-y-08',
    bookNo: '三·例四·图85',
    title: '有炮须留他家士（不宜吃士）',
    category: '增订·棋谚图解',
    difficulty: 4,
    fen: '4ka3/6a2/9/9/4C3N/9/9/9/3pp2p1/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '马六进七勿吃士；马七退八、马八退六禁将后炮六平四胜。',
  },
  {
    id: 'x-y-09',
    bookNo: '四·例一·图86',
    title: '残棋最忌车头低（诱车入底）',
    category: '增订·棋谚图解',
    difficulty: 3,
    fen: '4k4/9/9/9/4r4/9/1N7/7R1/4A4/C2K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '利而诱之，把黑车引入底线；车八平五、马二进一、炮一平六绝杀。',
  },
  {
    id: 'x-y-10',
    bookNo: '四·例二·图87',
    title: '残棋最忌车头低（古局）',
    category: '增订·棋谚图解',
    difficulty: 4,
    fen: '2a1kb3/3a5/1P1b1N3/3p5/9/8n/3B5/7Cr/3A5/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '利用黑方车头低；兵三平二、炮一进七、马四退三连环攻杀。',
  },
  {
    id: 'x-y-11',
    bookNo: '五·例一·图88',
    title: '缺士怕双车',
    category: '增订·棋谚图解',
    difficulty: 4,
    fen: '1bak5/3a5/r2b5/1npp1p1p1/nr6p/1PRP3PP/1R7/3B5/3A5/1B1KA4 w',
    winSide: 'red',
    goal: 'win',
    tip: '马七进五弃子破士，双车追杀；缺士方最忌此势。',
  },
  {
    id: 'x-y-12',
    bookNo: '五·例二·图89',
    title: '缺士怕双车（献炮破士）',
    category: '增订·棋谚图解',
    difficulty: 4,
    fen: '2a1k4/2ab1C3/5rC1p/1b1p5/9/PPRP3PP/9/2R6/3A1B1R1/3KA4 w',
    winSide: 'red',
    goal: 'win',
    tip: '黑多卒似优；炮七进三献炮破士，双车入局反胜。',
  },

  // ========== 增订·实战残局选评 ==========
  {
    id: 'x-z-01',
    bookNo: '一·图90',
    title: '车卒能和车炮士',
    category: '增订·实战选评',
    difficulty: 4,
    fen: '3k5/9/9/3r5/9/3pR4/9/8C/5A3/4K4 w',
    winSide: 'red',
    goal: 'draw',
    tip: '实战选评：车卒守和车炮士。',
  },
  {
    id: 'x-z-02',
    bookNo: '二·图92',
    title: '残棋炮归家',
    category: '增订·实战选评',
    difficulty: 3,
    fen: '3k1a3/3p3C1/3r1a1P1/b8/9/3CR4/9/5A3/4B4/2BAK4 w',
    winSide: 'red',
    goal: 'win',
    tip: '实战中炮归家控局。',
  },
  {
    id: 'x-z-03',
    bookNo: '三·图94',
    title: '三仙炼丹的基本杀势',
    category: '增订·实战选评',
    difficulty: 4,
    fen: '3aka3/9/4bb3/9/2R6/9/4p4/p7p/3BA4/4KB3 w',
    winSide: 'red',
    goal: 'win',
    tip: '三兵「炼丹」杀势与推论法。',
  },

  // ========== 增订·看杀局练心算（四步杀 A-1～A-10） ==========
  {
    id: 'x-s-01',
    bookNo: 'A-1',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '2bakab2/8N/7r1/9/9/5r3/9/4BC3/1p1p1p1p1/4K4 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀；心算练习，答案见书末揭晓。',
  },
  {
    id: 'x-s-02',
    bookNo: 'A-2',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '4kab1C/4a3R/4b4/9/9/9/9/5R2B/2N1A1pp1/3AK4 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
  {
    id: 'x-s-03',
    bookNo: 'A-3',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '4r4/3k5/3a5/9/C8/1N7/9/7n1/4p1r2/4AK3 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
  {
    id: 'x-s-04',
    bookNo: 'A-4',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '5k3/4a1R2/5a3/5Nb2/9/9/9/2n6/4pC3/1CRAKA3 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
  {
    id: 'x-s-05',
    bookNo: 'A-5',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '3kab3/3a5/3b5/1NN6/9/9/5p3/4K4/9/3n5 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
  {
    id: 'x-s-06',
    bookNo: 'A-6',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '1bak5/1N1a1RR2/3b1C3/5p3/2n6/9/9/2K6/1r1r5/5C3 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
  {
    id: 'x-s-07',
    bookNo: 'A-7',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '3ka4/3a5/9/7N1/4R1R2/9/9/9/1rr1p4/3K5 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
  {
    id: 'x-s-08',
    bookNo: 'A-8',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '3ka4/3a2R2/2cb1C3/9/2r6/9/5C3/9/2pCrnc2/3KA4 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
  {
    id: 'x-s-09',
    bookNo: 'A-9',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '3kb4/2R6/N6b1/9/9/9/9/C4n3/4R4/2AK3C1 w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
  {
    id: 'x-s-10',
    bookNo: 'A-10',
    title: '四步杀',
    category: '增订·看杀局练心算',
    difficulty: 3,
    fen: '2ak5/3a5/5N3/9/9/9/9/4R2C1/3pp4/1NAK4c w',
    winSide: 'red',
    goal: 'win',
    tip: '红先四步杀。',
  },
]

export function getPuzzle(id: string): Puzzle | undefined {
  return PUZZLES.find((p) => p.id === id)
}

export function puzzlesByCategory(category: string): Puzzle[] {
  return PUZZLES.filter((p) => p.category === category)
}

export function nextPuzzleId(id: string): string | null {
  const i = PUZZLES.findIndex((p) => p.id === id)
  if (i < 0 || i >= PUZZLES.length - 1) return null
  return PUZZLES[i + 1].id
}
