#!/usr/bin/env python3
"""Build Xiangqi FEN from piece list. rank 0=top, file 1-9 left to right."""

from __future__ import annotations

import sys

KIND = {
    ('red', 'K'): 'K',
    ('red', 'A'): 'A',
    ('red', 'B'): 'B',
    ('red', 'N'): 'N',
    ('red', 'R'): 'R',
    ('red', 'C'): 'C',
    ('red', 'P'): 'P',
    ('black', 'K'): 'k',
    ('black', 'A'): 'a',
    ('black', 'B'): 'b',
    ('black', 'N'): 'n',
    ('black', 'R'): 'r',
    ('black', 'C'): 'c',
    ('black', 'P'): 'p',
}


def build_fen(pieces: list[tuple[str, str, int, int]], stm: str = 'w') -> str:
    grid: list[list[str | None]] = [[None] * 9 for _ in range(10)]
    for side, kind, rank, file1 in pieces:
        ch = KIND[(side, kind)]
        f = file1 - 1
        if grid[rank][f] is not None:
            raise ValueError(f'overlap at rank={rank} file={file1}: {grid[rank][f]} vs {ch}')
        grid[rank][f] = ch
    rows: list[str] = []
    for rank in range(10):
        row = ''
        empty = 0
        for f in range(9):
            ch = grid[rank][f]
            if ch is None:
                empty += 1
            else:
                if empty:
                    row += str(empty)
                    empty = 0
                row += ch
        if empty:
            row += str(empty)
        if row == '':
            row = '9'
        rows.append(row)
    return '/'.join(rows) + f' {stm}'


if __name__ == '__main__':
    name = sys.argv[1]
    specs = {
        'fig18': (
            [
                ('black', 'K', 0, 5),
                ('black', 'N', 7, 2),
                ('black', 'P', 5, 4),
                ('red', 'K', 8, 6),
                ('red', 'A', 8, 5),
                ('red', 'A', 9, 6),
                ('red', 'B', 9, 3),
            ],
            'w',
        ),
        'fig17': (
            [
                ('black', 'K', 0, 5),
                ('black', 'N', 3, 9),
                ('black', 'P', 1, 4),
                ('red', 'K', 8, 6),
                ('red', 'A', 9, 6),
                ('red', 'B', 2, 1),
                ('red', 'B', 2, 5),
            ],
            'w',
        ),
        'fig1': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 4),
                ('black', 'A', 2, 6),
                ('black', 'P', 5, 8),
                ('red', 'N', 6, 3),
                ('red', 'P', 7, 5),
                ('red', 'K', 9, 5),
                ('red', 'B', 9, 7),
            ],
            'w',
        ),
        'fig2': (
            [
                ('black', 'K', 1, 6),
                ('black', 'A', 1, 5),
                ('black', 'A', 2, 7),
                ('black', 'P', 5, 6),
                ('red', 'N', 6, 2),
                ('red', 'P', 7, 5),
                ('red', 'K', 9, 5),
                ('red', 'B', 9, 6),
            ],
            'w',
        ),
        'fig71': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 6),
                ('black', 'A', 1, 4),
                ('black', 'R', 1, 8),
                ('black', 'P', 6, 9),
                ('red', 'R', 8, 8),
                ('red', 'N', 6, 8),
                ('red', 'K', 9, 5),
                ('red', 'A', 9, 6),
            ],
            'w',
        ),
        'fig78': (
            [
                ('black', 'K', 0, 6),
                ('black', 'A', 1, 5),
                ('black', 'A', 2, 4),
                ('black', 'B', 0, 4),
                ('black', 'B', 2, 5),
                ('black', 'N', 1, 4),
                ('black', 'N', 5, 9),
                ('red', 'K', 9, 5),
                ('red', 'A', 8, 4),
                ('red', 'B', 9, 3),
                ('red', 'B', 8, 5),
                ('red', 'N', 0, 9),
            ],
            'w',
        ),
        'fig79': (
            [
                ('black', 'K', 0, 6),
                ('black', 'A', 1, 5),
                ('black', 'A', 2, 4),
                ('black', 'B', 0, 4),
                ('black', 'B', 2, 5),
                ('black', 'N', 4, 6),
                ('red', 'N', 3, 9),
                ('red', 'N', 5, 4),
                ('red', 'K', 9, 5),
                ('red', 'A', 8, 5),
                ('red', 'B', 9, 6),
                ('red', 'B', 9, 3),
            ],
            'w',
        ),
        'fig80': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 1, 6),
                ('black', 'R', 5, 6),
                ('red', 'K', 9, 5),
                ('red', 'C', 9, 7),
                ('red', 'N', 9, 8),
            ],
            'w',
        ),
        'fig81': (
            [
                ('black', 'K', 0, 5),
                ('black', 'R', 6, 8),
                ('red', 'K', 9, 5),
                ('red', 'A', 8, 6),
                ('red', 'B', 9, 7),
                ('red', 'C', 3, 5),
                ('red', 'P', 3, 9),
            ],
            'w',
        ),
        'a1': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 4),
                ('black', 'A', 0, 6),
                ('black', 'B', 0, 3),
                ('black', 'B', 0, 7),
                ('black', 'R', 2, 8),
                ('black', 'R', 5, 6),
                ('black', 'P', 8, 2),
                ('black', 'P', 8, 4),
                ('black', 'P', 8, 6),
                ('black', 'P', 8, 8),
                ('red', 'K', 9, 5),
                ('red', 'B', 7, 5),
                ('red', 'C', 7, 6),
                ('red', 'N', 1, 9),
            ],
            'w',
        ),
        'fig72': (
            [
                ('black', 'K', 1, 5),
                ('black', 'A', 0, 5),
                ('black', 'P', 3, 7),
                ('black', 'R', 4, 6),
                ('black', 'N', 4, 5),
                ('red', 'K', 9, 5),
                ('red', 'B', 9, 7),
                ('red', 'R', 5, 8),
                ('red', 'N', 4, 4),
                ('red', 'N', 5, 5),
            ],
            'w',
        ),
        'fig73': (
            [
                ('black', 'K', 0, 6),
                ('black', 'B', 4, 1),
                ('black', 'R', 3, 5),
                ('red', 'K', 9, 5),
                ('red', 'A', 8, 6),
                ('red', 'R', 6, 5),
                ('red', 'N', 5, 5),
            ],
            'w',
        ),
        'fig82': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 4),
                ('black', 'A', 1, 5),
                ('black', 'B', 6, 9),
                ('black', 'P', 5, 1),
                ('red', 'K', 9, 5),
                ('red', 'C', 4, 8),
                ('red', 'P', 8, 6),
            ],
            'w',
        ),
        'fig86': (
            [
                ('black', 'K', 0, 5),
                ('black', 'R', 4, 5),
                ('red', 'K', 9, 4),
                ('red', 'A', 8, 5),
                ('red', 'C', 9, 1),
                ('red', 'N', 6, 2),
                ('red', 'R', 7, 8),
            ],
            'w',
        ),
        'fig74': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 4),
                ('black', 'A', 0, 6),
                ('black', 'R', 6, 1),
                ('black', 'C', 2, 5),
                ('black', 'P', 8, 4),
                ('red', 'K', 9, 5),
                ('red', 'A', 9, 6),
                ('red', 'R', 8, 5),
                ('red', 'N', 7, 5),
                ('red', 'C', 9, 9),
            ],
            'w',
        ),
        'fig83': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 4),
                ('black', 'A', 0, 6),
                ('black', 'B', 4, 7),
                ('black', 'C', 4, 8),
                ('red', 'K', 9, 6),
                ('red', 'C', 3, 6),
                ('red', 'P', 8, 5),
            ],
            'w',
        ),
        'fig85': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 6),
                ('black', 'A', 1, 7),
                ('black', 'P', 8, 4),
                ('black', 'P', 8, 5),
                ('black', 'P', 8, 8),
                ('red', 'K', 9, 5),
                ('red', 'C', 4, 5),
                ('red', 'N', 4, 9),
            ],
            'w',
        ),
        'a2': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 6),
                ('black', 'A', 1, 5),
                ('black', 'B', 0, 7),
                ('black', 'B', 2, 5),
                ('black', 'P', 8, 7),
                ('black', 'P', 8, 8),
                ('red', 'K', 9, 5),
                ('red', 'A', 8, 5),
                ('red', 'A', 9, 4),
                ('red', 'B', 7, 9),
                ('red', 'N', 8, 3),
                ('red', 'R', 1, 9),
                ('red', 'R', 7, 6),
                ('red', 'C', 0, 9),
            ],
            'w',
        ),
        'a3': (
            [
                ('black', 'K', 1, 4),
                ('black', 'A', 2, 4),
                ('black', 'R', 0, 5),
                ('black', 'R', 8, 7),
                ('black', 'N', 7, 8),
                ('black', 'P', 8, 5),
                ('red', 'K', 9, 6),
                ('red', 'A', 9, 5),
                ('red', 'N', 5, 2),
                ('red', 'C', 4, 1),
            ],
            'w',
        ),
        'a4': (
            [
                ('black', 'K', 0, 6),
                ('black', 'A', 1, 5),
                ('black', 'A', 2, 6),
                ('black', 'B', 3, 7),
                ('black', 'N', 7, 3),
                ('black', 'P', 8, 5),
                ('red', 'K', 9, 5),
                ('red', 'A', 9, 4),
                ('red', 'A', 9, 6),
                ('red', 'R', 1, 7),
                ('red', 'R', 9, 3),
                ('red', 'N', 3, 6),
                ('red', 'C', 8, 6),
                ('red', 'C', 9, 2),
            ],
            'w',
        ),
        'fig75': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 1, 4),
                ('black', 'A', 2, 5),
                ('black', 'B', 0, 2),
                ('black', 'B', 3, 0),
                ('black', 'R', 2, 4),
                ('black', 'R', 5, 4),
                ('red', 'K', 9, 4),
                ('red', 'A', 8, 4),
                ('red', 'B', 7, 0),
                ('red', 'R', 7, 1),
                ('red', 'R', 7, 2),
                ('red', 'P', 4, 8),
            ],
            'w',
        ),
        'fig76': (
            [
                ('black', 'K', 2, 5),
                ('black', 'B', 3, 4),
                ('black', 'P', 4, 4),
                ('black', 'R', 8, 1),
                ('red', 'K', 9, 4),
                ('red', 'P', 6, 0),
                ('red', 'P', 6, 6),
                ('red', 'P', 7, 8),
                ('red', 'R', 8, 8),
            ],
            'b',
        ),
        'test77': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 1, 3),
                ('black', 'A', 1, 5),
                ('black', 'B', 2, 8),
                ('black', 'B', 3, 6),
                ('black', 'P', 6, 0),
                ('red', 'P', 0, 2),
                ('red', 'P', 0, 3),
                ('red', 'P', 0, 7),
                ('red', 'P', 3, 8),
                ('red', 'P', 7, 0),
                ('red', 'C', 8, 4),
                ('red', 'R', 8, 6),
                ('red', 'K', 9, 4),
            ],
            'w',
        ),
        'test78': (
            [
                ('black', 'K', 0, 5),
                ('black', 'A', 0, 4),
                ('black', 'A', 1, 5),
                ('black', 'B', 0, 6),
                ('black', 'R', 2, 8),
                ('black', 'R', 8, 5),
                ('black', 'C', 3, 0),
                ('black', 'P', 7, 5),
                ('red', 'K', 9, 4),
                ('red', 'A', 9, 5),
                ('red', 'B', 5, 7),
                ('red', 'B', 7, 8),
                ('red', 'N', 8, 1),
                ('red', 'P', 7, 2),
            ],
            'w',
        ),
        'fig84': (
            [
                ('black', 'K', 0, 4),
                ('black', 'A', 0, 3),
                ('black', 'A', 0, 5),
                ('red', 'C', 4, 7),
                ('red', 'C', 5, 7),
                ('red', 'C', 6, 4),
                ('red', 'B', 7, 4),
                ('red', 'K', 9, 4),
            ],
            'w',
        ),
        'fig87': (
            [
                ('black', 'A', 0, 3),
                ('black', 'K', 0, 5),
                ('black', 'B', 0, 6),
                ('black', 'A', 1, 4),
                ('black', 'B', 2, 4),
                ('black', 'P', 3, 4),
                ('black', 'N', 5, 0),
                ('black', 'R', 7, 0),
                ('red', 'P', 2, 2),
                ('red', 'N', 2, 6),
                ('red', 'B', 6, 4),
                ('red', 'C', 7, 8),
                ('red', 'A', 8, 4),
                ('red', 'K', 9, 5),
            ],
            'w',
        ),
        'fig88': (
            [
                ('black', 'B', 0, 2),
                ('black', 'A', 0, 3),
                ('black', 'K', 0, 4),
                ('black', 'A', 1, 4),
                ('black', 'B', 2, 4),
                ('black', 'R', 2, 1),
                ('black', 'N', 3, 2),
                ('black', 'P', 3, 3),
                ('black', 'P', 3, 4),
                ('black', 'P', 3, 6),
                ('black', 'P', 3, 8),
                ('black', 'P', 4, 0),
                ('black', 'N', 4, 1),
                ('black', 'R', 4, 2),
                ('red', 'P', 5, 8),
                ('red', 'P', 5, 4),
                ('red', 'R', 5, 3),
                ('red', 'P', 5, 2),
                ('red', 'P', 5, 0),
                ('red', 'R', 6, 2),
                ('red', 'B', 7, 4),
                ('red', 'A', 8, 4),
                ('red', 'K', 9, 4),
                ('red', 'A', 9, 5),
                ('red', 'B', 9, 2),
            ],
            'w',
        ),
        'fig89': (
            [
                ('black', 'A', 0, 3),
                ('black', 'K', 0, 5),
                ('black', 'A', 1, 3),
                ('black', 'B', 1, 4),
                ('black', 'P', 2, 0),
                ('black', 'R', 2, 6),
                ('black', 'B', 3, 2),
                ('black', 'P', 3, 4),
                ('red', 'C', 1, 6),
                ('red', 'C', 2, 7),
                ('red', 'P', 5, 8),
                ('red', 'R', 5, 3),
                ('red', 'P', 5, 4),
                ('red', 'P', 5, 2),
                ('red', 'P', 5, 1),
                ('red', 'P', 5, 0),
                ('red', 'R', 7, 3),
                ('red', 'R', 8, 8),
                ('red', 'B', 8, 6),
                ('red', 'A', 8, 4),
                ('red', 'A', 9, 5),
                ('red', 'K', 9, 4),
            ],
            'w',
        ),
        'a5': (
            [
                ('black', 'K', 0, 4),
                ('black', 'A', 0, 5),
                ('black', 'A', 1, 4),
                ('black', 'B', 0, 6),
                ('black', 'B', 2, 4),
                ('black', 'P', 6, 6),
                ('black', 'N', 9, 4),
                ('red', 'N', 3, 2),
                ('red', 'N', 3, 3),
                ('red', 'K', 7, 5),
            ],
            'w',
        ),
        'a6': (
            [
                ('black', 'K', 0, 4),
                ('black', 'A', 0, 3),
                ('black', 'A', 1, 4),
                ('black', 'B', 0, 2),
                ('black', 'B', 2, 4),
                ('black', 'P', 3, 6),
                ('black', 'N', 4, 3),
                ('black', 'R', 8, 2),
                ('black', 'R', 8, 4),
                ('red', 'N', 1, 2),
                ('red', 'R', 1, 6),
                ('red', 'R', 1, 7),
                ('red', 'C', 2, 6),
                ('red', 'K', 7, 3),
                ('red', 'C', 9, 6),
            ],
            'w',
        ),
        'a7': (
            [
                ('black', 'K', 0, 4),
                ('black', 'A', 0, 5),
                ('black', 'A', 1, 4),
                ('black', 'R', 8, 2),
                ('black', 'R', 8, 3),
                ('black', 'P', 8, 5),
                ('red', 'N', 3, 8),
                ('red', 'R', 4, 5),
                ('red', 'R', 4, 7),
                ('red', 'K', 9, 4),
            ],
            'w',
        ),
        'a8': (
            [
                ('black', 'K', 0, 4),
                ('black', 'A', 0, 5),
                ('black', 'A', 1, 4),
                ('black', 'B', 2, 4),
                ('black', 'C', 2, 3),
                ('black', 'R', 4, 3),
                ('black', 'R', 8, 5),
                ('black', 'P', 8, 3),
                ('black', 'N', 8, 6),
                ('black', 'C', 8, 7),
                ('red', 'R', 1, 7),
                ('red', 'C', 2, 6),
                ('red', 'C', 6, 6),
                ('red', 'C', 8, 4),
                ('red', 'K', 9, 4),
                ('red', 'A', 9, 5),
            ],
            'w',
        ),
        'a9': (
            [
                ('black', 'K', 0, 4),
                ('black', 'B', 0, 5),
                ('red', 'R', 1, 3),
                ('red', 'N', 2, 1),
                ('black', 'B', 2, 8),
                ('red', 'C', 7, 1),
                ('black', 'N', 7, 6),
                ('red', 'R', 8, 5),
                ('red', 'A', 9, 3),
                ('red', 'K', 9, 4),
                ('red', 'C', 9, 8),
            ],
            'w',
        ),
        'a10': (
            [
                ('black', 'A', 0, 3),
                ('black', 'K', 0, 4),
                ('black', 'A', 1, 4),
                ('red', 'N', 2, 6),
                ('red', 'R', 7, 5),
                ('red', 'C', 7, 8),
                ('black', 'P', 8, 4),
                ('black', 'P', 8, 5),
                ('black', 'C', 9, 0),
                ('red', 'N', 9, 2),
                ('red', 'A', 9, 3),
                ('red', 'K', 9, 4),
            ],
            'w',
        ),
    }
    pieces, stm = specs[name]
    print(build_fen(pieces, stm))
